### ISSUE TITLE
Provided API should use AsRef<Path> instead of Into<String>

### ISSUE THREAD

**Issue by xabufr** [GandalfTheGrayOfHell/tfio#1]
Path may not be only strings, using `Path` and `PathBuf` with the generic `AsRef<Path>` will provide a more generic API.

**Comment by MovAh13h** [comment]
Will update over the weekend

**Comment by MovAh13h** [comment]
Can you send a PR for both the issues? I'll update cargo tomorrow and then it should be good for you to use?
